project_id = "kfqnrdnwnmzawajybytr"

[functions.generate-forecast]
verify_jwt = false

[functions.generate-strategic-forecast]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.save-forecast]
verify_jwt = false

[functions.update-free-forecast-email]
verify_jwt = false

[functions.send-forecast-email]
verify_jwt = false

[functions.geocode-place]
verify_jwt = false
