project_id = "kfqnrdnwnmzawajybytr"

[functions.generate-forecast]
verify_jwt = false

[functions.generate-paid-forecast]
verify_jwt = false

[functions.get-forecast]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.update-free-forecast-email]
verify_jwt = false

[functions.send-forecast-email]
verify_jwt = false

[functions.geocode-place]
verify_jwt = false

[functions.notify-support]
verify_jwt = false

[functions.get-timezone]
verify_jwt = false
