project_id = "kfqnrdnwnmzawajybytr"

[functions.generate-forecast]
verify_jwt = false

[functions.generate-paid-forecast]
verify_jwt = false

[functions.get-forecast]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.update-free-forecast-email]
verify_jwt = false

[functions.send-forecast-email]
verify_jwt = false

[functions.geocode-place]
verify_jwt = false

[functions.notify-support]
verify_jwt = false

[functions.get-timezone]
verify_jwt = false

[functions.get-advanced-kundli]
verify_jwt = false

[functions.save-kundli-details]
verify_jwt = false

[functions.debug-llm-payload]
verify_jwt = false

[functions.update-kundli-details]
verify_jwt = false

[functions.save-birth-chart]
verify_jwt = false

[functions.calculate-dasha-periods]
verify_jwt = false

[functions.get-kundli-data]
verify_jwt = false

[functions.generate-free-vedic-forecast]
verify_jwt = false

[functions.generate-paid-vedic-forecast]
verify_jwt = false

[functions.create-vedic-payment]
verify_jwt = false

[functions.get-birth-chart]
verify_jwt = false

[functions.get-vedic-kundli-details]
verify_jwt = false

[functions.link-forecast-to-user]
verify_jwt = false
